"""
G-code parsing utilities for Bambu Studio sliced files.

Provides functions to extract structured information from G-code content,
including layer detection, feature classification, move parsing, and
print statistics extraction.

Bambu Studio G-code Comment Format
-----------------------------------
Bambu Studio annotates its G-code with structured comments:

    ; CHANGE_LAYER          — layer boundary
    ; Z_HEIGHT: 0.400       — current Z height in mm
    ; FEATURE: Outer wall   — start of outer perimeter
    ; FEATURE: Inner wall   — start of inner perimeter(s)
    ; FEATURE: Sparse infill — start of sparse infill
    ; FEATURE: Solid infill — start of solid infill (top/bottom)
    ; FEATURE: Bridge       — bridging section
    ; FEATURE: Overhang wall — overhang perimeter
    ; FEATURE: Support       — support structure
    ; WIPE_START / WIPE_END — filament wipe moves

These comments are essential for the post-processors to identify which
sections of G-code to modify.
"""

import re
from dataclasses import dataclass, field
from typing import List, Optional, Tuple


@dataclass
class GcodeMove:
    """A single parsed G-code movement command.

    Attributes
    ----------
    x, y, z : float or None
        Target coordinates. None means the axis is not specified in this
        command (i.e., it stays at its current position).
    e : float or None
        Extrusion amount. None for travel moves (no extrusion).
        Positive values indicate material deposition.
    f : int or None
        Feedrate in mm/min. None means use the previous feedrate.
    is_travel : bool
        True if this is a non-extruding repositioning move.
    line_number : int
        Original line number in the G-code file.
    """
    x: Optional[float] = None
    y: Optional[float] = None
    z: Optional[float] = None
    e: Optional[float] = None
    f: Optional[int] = None
    is_travel: bool = False
    line_number: int = 0


@dataclass
class GcodeLayer:
    """A parsed G-code layer with classified features.

    Attributes
    ----------
    layer_index : int
        Zero-based layer number.
    z_height : float
        Z height of this layer in mm.
    features : dict
        Dictionary mapping feature names to lists of GcodeMove objects.
        Feature names include: 'Inner wall', 'Outer wall', 'Sparse infill',
        'Solid infill', 'Bridge', 'Support', etc.
    raw_lines : list of str
        Original G-code lines for this layer.
    """
    layer_index: int = 0
    z_height: float = 0.0
    features: dict = field(default_factory=dict)
    raw_lines: List[str] = field(default_factory=list)


def parse_move(line: str) -> Optional[GcodeMove]:
    """Parse a single G0 or G1 command into a GcodeMove object.

    Parameters
    ----------
    line : str
        A G-code line (e.g., "G1 X105.2 Y110.5 E0.035 F3000").

    Returns
    -------
    GcodeMove or None
        Parsed move, or None if the line is not a G0/G1 command.
    """
    stripped = line.strip()
    if not stripped.startswith(('G0', 'G1', 'g0', 'g1')):
        return None

    move = GcodeMove()

    x_match = re.search(r'X([\d.]+)', stripped, re.IGNORECASE)
    y_match = re.search(r'Y([\d.]+)', stripped, re.IGNORECASE)
    z_match = re.search(r'Z([\d.]+)', stripped, re.IGNORECASE)
    e_match = re.search(r'E([\d.]+)', stripped, re.IGNORECASE)
    f_match = re.search(r'F(\d+)', stripped, re.IGNORECASE)

    if x_match:
        move.x = float(x_match.group(1))
    if y_match:
        move.y = float(y_match.group(1))
    if z_match:
        move.z = float(z_match.group(1))
    if e_match:
        move.e = float(e_match.group(1))
    if f_match:
        move.f = int(f_match.group(1))

    move.is_travel = (move.e is None or move.e == 0)
    return move


def detect_slicer(gcode_content: str) -> str:
    """Detect which slicer generated the G-code.

    Parameters
    ----------
    gcode_content : str
        G-code content to analyze.

    Returns
    -------
    str
        Slicer name: 'bambu_studio', 'prusaslicer', 'cura', or 'unknown'.
    """
    if 'BambuStudio' in gcode_content or 'bambu' in gcode_content.lower():
        return 'bambu_studio'
    if 'PrusaSlicer' in gcode_content or 'generated by PrusaSlicer' in gcode_content:
        return 'prusaslicer'
    if 'Cura' in gcode_content or 'FLAVOR:Marlin' in gcode_content:
        return 'cura'
    return 'unknown'


def count_layers(gcode_content: str) -> int:
    """Count the number of layers in G-code content."""
    return len(re.findall(r';\s*CHANGE_LAYER', gcode_content, re.IGNORECASE))


def extract_print_settings(gcode_content: str) -> dict:
    """Extract print settings from G-code comments.

    Bambu Studio embeds print settings as comments at the beginning
    of the G-code file.

    Returns
    -------
    dict
        Dictionary of setting name to value (all values as strings).
    """
    settings = {}
    # Bambu Studio format: "; setting_name = value"
    for match in re.finditer(r'^;\s*(\w+)\s*=\s*(.+)$', gcode_content, re.MULTILINE):
        settings[match.group(1).strip()] = match.group(2).strip()
    return settings
